# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
AllCops:
  NewCops: enable
  Exclude:
    - 'frontend/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Style/StringLiterals:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false
